# Generated by Django 4.2 on 2023-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(max_length=1000, verbose_name='Kommentti'),
        ),
    ]
